Add addPass helper

diff --git a/localrc b/localrc
--- a/localrc
+++ b/localrc
@@ -105,6 +105,34 @@ logs_nginx() {
     sudo tail -f ${logs_path}
 }
 
+function addPass() {
+    local RED='\033[0;31m'
+    local GREEN='\033[0;32m'
+    local RESET='\033[0m'
+
+    if ! command -v pass 1>/dev/null 2>&1; then
+        echo -e "${RED}pass not found, aborting${RESET}"
+        return 1
+    fi
+
+    if [[ "${#}" -eq 0 ]]; then
+        echo -e "${RED}Usage addPass [folder]/[name] (e.g. addPass commons/wifi)${RESET}"
+        return 1
+    fi
+
+    echo -e "${GREEN}Updating password store${RESET}"
+    echo
+    pass git pull
+
+    echo -e "${GREEN}Importing public keys of team${RESET}"
+    echo
+    ls ~/.password-store/.public_keys/*.gpg | xargs gpg --import
+
+    echo -e "${GREEN}Adding password, don't forget to run command 'pass git push' when ended${RESET}"
+    echo
+    pass insert -m "${@}"
+}
+
 # The next line updates PATH for the Google Cloud SDK.
 if [ -f '/home/jonathanc/google-cloud-sdk/path.zsh.inc' ]; then . '/home/jonathanc/google-cloud-sdk/path.zsh.inc'; fi
 
